# Phase 51: Secrets Manager containers for every credential the app
# needs at runtime, so no literal secret value is ever declared,
# variabled, or defaulted in Terraform. Two different patterns are
# used depending on where the value comes from:
#
#   - Externally issued credentials (Google OAuth client secret,
#     Anthropic/OpenAI API keys) can't be generated by Terraform at
#     all — only the secret *container* is created here. Its value is
#     populated out-of-band (console or `aws secretsmanager
#     put-secret-value`) once a real AWS account exists; see
#     infra/aws/README.md.
#
#   - The app's own JWT signing key isn't issued by anyone external,
#     so it's safe (and better) to have Terraform generate a random
#     value itself via the `random` provider and store *that* in
#     Secrets Manager — the random value lives in Terraform state, not
#     as a literal in any .tf file, and is unique per environment.
#
# Database credentials are handled separately: RDS's own
# `manage_master_user_password` (Phase 46) already means Terraform
# never sees a DB password at all, so this module doesn't duplicate
# that — it only exists for credentials outside RDS's control.

terraform {
  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

resource "aws_secretsmanager_secret" "oauth_client_secret" {
  name        = "${var.name_prefix}-oauth-client-secret"
  description = "Google OAuth client secret (OAUTH_CLIENT_SECRET). Populated out-of-band — not managed by Terraform."

  tags = var.tags
}

resource "aws_secretsmanager_secret" "anthropic_api_key" {
  name        = "${var.name_prefix}-anthropic-api-key"
  description = "Anthropic API key (ANTHROPIC_API_KEY). Populated out-of-band — not managed by Terraform."

  tags = var.tags
}

resource "aws_secretsmanager_secret" "openai_api_key" {
  name        = "${var.name_prefix}-openai-api-key"
  description = "OpenAI API key (OPENAI_API_KEY). Populated out-of-band — not managed by Terraform."

  tags = var.tags
}

# The app secret is the one credential Terraform is allowed to
# generate itself, since nothing external issues it.
resource "random_password" "jwt_secret_key" {
  length  = 64
  special = true
}

resource "aws_secretsmanager_secret" "jwt_secret_key" {
  name        = "${var.name_prefix}-jwt-secret-key"
  description = "Session JWT signing key (JWT_SECRET_KEY). Generated by Terraform via the random provider."

  tags = var.tags
}

resource "aws_secretsmanager_secret_version" "jwt_secret_key" {
  secret_id     = aws_secretsmanager_secret.jwt_secret_key.id
  secret_string = random_password.jwt_secret_key.result
}
