import enum
import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import Enum as SqlEnum
from sqlalchemy import ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.models.types import created_at_column, uuid_pk

if TYPE_CHECKING:
    from app.models.chunk import DocumentChunk
    from app.models.document import Document
    from app.models.project import Project


class ReportType(enum.StrEnum):
    """Not in docs/domain-model.md's original sketch (that document
    predates Phase 24) — a workflow beyond chat, built on the same
    retrieval+generation+citation machinery as RAG chat (Phase 19), just
    run as a background job over a fixed set of section prompts per type
    (see app/reports/templates.py) instead of one ad-hoc question."""

    EXECUTIVE_SUMMARY = "executive_summary"
    EVIDENCE_REPORT = "evidence_report"
    RISK_ANALYSIS = "risk_analysis"
    CHRONOLOGY = "chronology"
    CONTRADICTION_REPORT = "contradiction_report"
    RESEARCH_MEMO = "research_memo"


class ReportStatus(enum.StrEnum):
    QUEUED = "queued"
    PROCESSING = "processing"
    READY = "ready"
    FAILED = "failed"


class Report(Base):
    __tablename__ = "reports"

    id: Mapped[uuid.UUID] = uuid_pk()
    project_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True
    )
    report_type: Mapped[ReportType] = mapped_column(
        SqlEnum(ReportType, native_enum=False, length=30), nullable=False
    )
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    status: Mapped[ReportStatus] = mapped_column(
        SqlEnum(ReportStatus, native_enum=False, length=20),
        nullable=False,
        default=ReportStatus.QUEUED,
    )
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_by: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="RESTRICT"), nullable=False
    )
    created_at: Mapped[datetime] = created_at_column()

    project: Mapped["Project"] = relationship()
    sections: Mapped[list["ReportSection"]] = relationship(
        back_populates="report", cascade="all, delete-orphan", order_by="ReportSection.position"
    )

    def __repr__(self) -> str:
        return f"<Report id={self.id} type={self.report_type} status={self.status}>"


class ReportSection(Base):
    """One section of a Report (e.g. "Timeline of Events") — generated by
    answering that section's prompt through the same RagService used for
    chat, so every section keeps its own citations (see ReportCitation)
    rather than the report as a whole having one undifferentiated source
    list.
    """

    __tablename__ = "report_sections"

    id: Mapped[uuid.UUID] = uuid_pk()
    report_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reports.id", ondelete="CASCADE"), nullable=False, index=True
    )
    heading: Mapped[str] = mapped_column(String(300), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    position: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = created_at_column()

    report: Mapped["Report"] = relationship(back_populates="sections")
    citations: Mapped[list["ReportCitation"]] = relationship(
        back_populates="section",
        cascade="all, delete-orphan",
        order_by="ReportCitation.source_number",
    )

    def __repr__(self) -> str:
        return f"<ReportSection id={self.id} heading={self.heading!r}>"


class ReportCitation(Base):
    """Same shape as app.models.citation.Citation, pointed at a
    ReportSection instead of a Message — kept as a separate table rather
    than making Citation's target polymorphic (nullable message_id +
    nullable report_section_id) so both tables keep a single, always-set,
    NOT NULL foreign key instead of an either/or that the DB can't enforce
    on its own.
    """

    __tablename__ = "report_citations"

    id: Mapped[uuid.UUID] = uuid_pk()
    section_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("report_sections.id", ondelete="CASCADE"), nullable=False, index=True
    )
    document_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), nullable=False
    )
    document_chunk_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("document_chunks.id", ondelete="CASCADE"), nullable=False
    )
    source_number: Mapped[int] = mapped_column(Integer, nullable=False)
    page_number: Mapped[int] = mapped_column(Integer, nullable=False)
    quote: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = created_at_column()

    section: Mapped["ReportSection"] = relationship(back_populates="citations")
    document: Mapped["Document"] = relationship()
    document_chunk: Mapped["DocumentChunk"] = relationship()

    def __repr__(self) -> str:
        return (
            f"<ReportCitation id={self.id} section={self.section_id} source={self.source_number}>"
        )
