"""Add prompt_versions and messages.prompt_version_id

Revision ID: 0005_add_prompt_versions
Revises: 0004_add_citations
Create Date: 2026-09-09 23:46:02.776170

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005_add_prompt_versions"
down_revision: str | None = "0004_add_citations"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", "version", name="uq_prompt_version"),
    )
    op.create_index(op.f("ix_prompt_versions_name"), "prompt_versions", ["name"], unique=False)
    op.create_index(
        op.f("ix_prompt_versions_project_id"), "prompt_versions", ["project_id"], unique=False
    )
    # batch_alter_table: SQLite can't ALTER TABLE ADD a foreign key
    # constraint directly (only Postgres can) — batch mode recreates the
    # table under the hood on SQLite and emits a plain ALTER on Postgres,
    # so this migration still serves both (see migration 0003's comment on
    # why the same migration file runs against both dialects).
    with op.batch_alter_table("messages") as batch_op:
        batch_op.add_column(sa.Column("prompt_version_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            "fk_messages_prompt_version_id",
            "prompt_versions",
            ["prompt_version_id"],
            ["id"],
            ondelete="SET NULL",
        )
    # Autogenerate also proposed an alter_column on document_chunks.embedding
    # (NUMERIC -> VECTOR) here — the same SQLite-reflection false positive
    # noted in migration 0004; omitted for the same reason.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages") as batch_op:
        batch_op.drop_constraint("fk_messages_prompt_version_id", type_="foreignkey")
        batch_op.drop_column("prompt_version_id")
    op.drop_index(op.f("ix_prompt_versions_project_id"), table_name="prompt_versions")
    op.drop_index(op.f("ix_prompt_versions_name"), table_name="prompt_versions")
    op.drop_table("prompt_versions")
    # ### end Alembic commands ###
