"""Add model_runs and messages.model_run_id

Revision ID: 0006_add_model_runs
Revises: 0005_add_prompt_versions
Create Date: 2026-09-09 23:55:47.513049

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006_add_model_runs"
down_revision: str | None = "0005_add_prompt_versions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version_id", sa.Uuid(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("SUCCEEDED", "FAILED", name="modelrunstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("retrieval_config", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["prompt_version_id"], ["prompt_versions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # batch_alter_table: see migration 0005's comment (SQLite can't ALTER
    # TABLE ADD a foreign key directly).
    with op.batch_alter_table("messages") as batch_op:
        batch_op.add_column(sa.Column("model_run_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            "fk_messages_model_run_id", "model_runs", ["model_run_id"], ["id"], ondelete="SET NULL"
        )
    # Autogenerate also proposed an alter_column on document_chunks.embedding
    # (NUMERIC -> VECTOR) here — the same SQLite-reflection false positive
    # noted in migrations 0004/0005; omitted for the same reason.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages") as batch_op:
        batch_op.drop_constraint("fk_messages_model_run_id", type_="foreignkey")
        batch_op.drop_column("model_run_id")
    op.drop_table("model_runs")
    # ### end Alembic commands ###
