"""Add human_reviews

Revision ID: 0010_add_human_reviews
Revises: 0009_add_model_run_project_user
Create Date: 2026-09-10 10:00:00.000000

Hand-written rather than autogenerated — this sandbox has no live
Postgres to autogenerate against (see migrations 0004-0009's same note).
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0010_add_human_reviews"
down_revision: str | None = "0009_add_model_run_project_user"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "human_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEEDS_REVIEW",
                "APPROVED",
                "REJECTED",
                "CORRECTED",
                name="humanreviewstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("flagged_by", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("original_answer", sa.Text(), nullable=False),
        sa.Column("corrected_answer", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["flagged_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_human_reviews_project_id"), "human_reviews", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_human_reviews_message_id"), "human_reviews", ["message_id"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_human_reviews_message_id"), table_name="human_reviews")
    op.drop_index(op.f("ix_human_reviews_project_id"), table_name="human_reviews")
    op.drop_table("human_reviews")
